backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "projects"
  label: "projects"
  folder: "src/projects"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown"}
    - { label: "Thumbnail", name: "thumbnail", widget: "image"}
    - { label: "Tags", name: "tags", widget: "list", default: ["projects"]}



# notes:
#label -> what we see on CMS UI
#name -> what it is called in code
